version: 0.2

env:
  parameter-store:
    ACCESS_KEY: "access-key-amplify-poc-dev"
    SECRET_KEY: "secret-key-amplify-poc-dev1"
    ENV: "amplify_ENV_dev"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - echo Build started...
      - aws configure set aws_access_key_id $ACCESS_KEY
      - aws configure set aws_secret_access_key $SECRET_KEY
      - aws configure set default.region $AWS_REGION
      - sh ./amplifyPush.sh -e $ENV
      - amplify publish
      - echo Build finished on `date`
artifacts:
  files:
    - "**/*"
